CC=g++
#CFLAGS=-Wall -ggdb -fPIC
CFLAGS=-ggdb
LINK =

#OBJ =

diction : diction.o
	$(CC) -o $@.out $<

xorq : xorq.o
	$(CC) -o $@.out $<

hanoi : hanoi.o
	$(CC) -o $@.out $<

uniqbeauti : uniqbeauti.o
	$(CC) -o $@.out $<

clean:
	rm -rf *.o
	rm -rf *.out
	rm -rf *.tmp
	rm -rf *~
